/*
 * nghttp2 - HTTP/2 C Library
 *
 * Copyright (c) 2026 nghttp2 contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#include "nghttp2_hpack.h"

#include <string.h>
#include <assert.h>

#include "nghttp2_macro.h"
#include "nghttp2_str.h"

#define DEBUGF(...)                                                            \
  do {                                                                         \
  } while (0)

/* Make scalar initialization form of nghttp2_hpack_entry */
#define MAKE_STATIC_ENT(N, V, T, H)                                            \
  {                                                                            \
    .nv =                                                                      \
      {                                                                        \
        .name =                                                                \
          &(nghttp2_rcbuf){                                                    \
            .base = (uint8_t *)(N),                                            \
            .len = nghttp2_strlen_lit((N)),                                    \
            .ref = -1,                                                         \
          },                                                                   \
        .value =                                                               \
          &(nghttp2_rcbuf){                                                    \
            .base = (uint8_t *)(V),                                            \
            .len = nghttp2_strlen_lit((V)),                                    \
            .ref = -1,                                                         \
          },                                                                   \
        .token = (T),                                                          \
      },                                                                       \
    .hash = (H),                                                               \
  }

/* Generated by mkstatictbl.py */
/* 3rd parameter is nghttp2_token value for header field name.  We use
   first enum value if same header names are repeated (e.g.,
   :status). */
static const nghttp2_hpack_static_entry static_table[] = {
  MAKE_STATIC_ENT(":authority", "", 0, 3153725150u),
  MAKE_STATIC_ENT(":method", "GET", 1, 695666056u),
  MAKE_STATIC_ENT(":method", "POST", 1, 695666056u),
  MAKE_STATIC_ENT(":path", "/", 3, 3292848686u),
  MAKE_STATIC_ENT(":path", "/index.html", 3, 3292848686u),
  MAKE_STATIC_ENT(":scheme", "http", 5, 2510477674u),
  MAKE_STATIC_ENT(":scheme", "https", 5, 2510477674u),
  MAKE_STATIC_ENT(":status", "200", 7, 4000288983u),
  MAKE_STATIC_ENT(":status", "204", 7, 4000288983u),
  MAKE_STATIC_ENT(":status", "206", 7, 4000288983u),
  MAKE_STATIC_ENT(":status", "304", 7, 4000288983u),
  MAKE_STATIC_ENT(":status", "400", 7, 4000288983u),
  MAKE_STATIC_ENT(":status", "404", 7, 4000288983u),
  MAKE_STATIC_ENT(":status", "500", 7, 4000288983u),
  MAKE_STATIC_ENT("accept-charset", "", 14, 3664010344u),
  MAKE_STATIC_ENT("accept-encoding", "gzip, deflate", 15, 3379649177u),
  MAKE_STATIC_ENT("accept-language", "", 16, 1979086614u),
  MAKE_STATIC_ENT("accept-ranges", "", 17, 1713753958u),
  MAKE_STATIC_ENT("accept", "", 18, 136609321u),
  MAKE_STATIC_ENT("access-control-allow-origin", "", 19, 2710797292u),
  MAKE_STATIC_ENT("age", "", 20, 742476188u),
  MAKE_STATIC_ENT("allow", "", 21, 2930878514u),
  MAKE_STATIC_ENT("authorization", "", 22, 2436257726u),
  MAKE_STATIC_ENT("cache-control", "", 23, 1355326669u),
  MAKE_STATIC_ENT("content-disposition", "", 24, 3889184348u),
  MAKE_STATIC_ENT("content-encoding", "", 25, 65203592u),
  MAKE_STATIC_ENT("content-language", "", 26, 24973587u),
  MAKE_STATIC_ENT("content-length", "", 27, 1308181789u),
  MAKE_STATIC_ENT("content-location", "", 28, 2302364718u),
  MAKE_STATIC_ENT("content-range", "", 29, 3555523146u),
  MAKE_STATIC_ENT("content-type", "", 30, 4244048277u),
  MAKE_STATIC_ENT("cookie", "", 31, 2007449791u),
  MAKE_STATIC_ENT("date", "", 32, 3564297305u),
  MAKE_STATIC_ENT("etag", "", 33, 113792960u),
  MAKE_STATIC_ENT("expect", "", 34, 2530896728u),
  MAKE_STATIC_ENT("expires", "", 35, 1049544579u),
  MAKE_STATIC_ENT("from", "", 36, 2513272949u),
  MAKE_STATIC_ENT("host", "", 37, 2952701295u),
  MAKE_STATIC_ENT("if-match", "", 38, 3597694698u),
  MAKE_STATIC_ENT("if-modified-since", "", 39, 2213050793u),
  MAKE_STATIC_ENT("if-none-match", "", 40, 2536202615u),
  MAKE_STATIC_ENT("if-range", "", 41, 2340978238u),
  MAKE_STATIC_ENT("if-unmodified-since", "", 42, 3794814858u),
  MAKE_STATIC_ENT("last-modified", "", 43, 3226950251u),
  MAKE_STATIC_ENT("link", "", 44, 232457833u),
  MAKE_STATIC_ENT("location", "", 45, 200649126u),
  MAKE_STATIC_ENT("max-forwards", "", 46, 1826162134u),
  MAKE_STATIC_ENT("proxy-authenticate", "", 47, 2709445359u),
  MAKE_STATIC_ENT("proxy-authorization", "", 48, 2686392507u),
  MAKE_STATIC_ENT("range", "", 49, 4208725202u),
  MAKE_STATIC_ENT("referer", "", 50, 3969579366u),
  MAKE_STATIC_ENT("refresh", "", 51, 3572655668u),
  MAKE_STATIC_ENT("retry-after", "", 52, 3336180598u),
  MAKE_STATIC_ENT("server", "", 53, 1085029842u),
  MAKE_STATIC_ENT("set-cookie", "", 54, 1848371000u),
  MAKE_STATIC_ENT("strict-transport-security", "", 55, 4138147361u),
  MAKE_STATIC_ENT("transfer-encoding", "", 56, 3719590988u),
  MAKE_STATIC_ENT("user-agent", "", 57, 606444526u),
  MAKE_STATIC_ENT("vary", "", 58, 1085005381u),
  MAKE_STATIC_ENT("via", "", 59, 1762798611u),
  MAKE_STATIC_ENT("www-authenticate", "", 60, 779865858u),
};

static int memeq(const void *s1, const void *s2, size_t n) {
  return memcmp(s1, s2, n) == 0;
}

/*
 * This function was generated by genlibtokenlookup.py.  Inspired by
 * h2o header lookup.  https://github.com/h2o/h2o
 */
static int32_t lookup_token(const uint8_t *name, size_t namelen) {
  switch (namelen) {
  case 2:
    switch (name[1]) {
    case 'e':
      if (memeq("t", name, 1)) {
        return NGHTTP2_HPACK_TOKEN_TE;
      }
      break;
    }
    break;
  case 3:
    switch (name[2]) {
    case 'a':
      if (memeq("vi", name, 2)) {
        return NGHTTP2_HPACK_TOKEN_VIA;
      }
      break;
    case 'e':
      if (memeq("ag", name, 2)) {
        return NGHTTP2_HPACK_TOKEN_AGE;
      }
      break;
    }
    break;
  case 4:
    switch (name[3]) {
    case 'e':
      if (memeq("dat", name, 3)) {
        return NGHTTP2_HPACK_TOKEN_DATE;
      }
      break;
    case 'g':
      if (memeq("eta", name, 3)) {
        return NGHTTP2_HPACK_TOKEN_ETAG;
      }
      break;
    case 'k':
      if (memeq("lin", name, 3)) {
        return NGHTTP2_HPACK_TOKEN_LINK;
      }
      break;
    case 'm':
      if (memeq("fro", name, 3)) {
        return NGHTTP2_HPACK_TOKEN_FROM;
      }
      break;
    case 't':
      if (memeq("hos", name, 3)) {
        return NGHTTP2_HPACK_TOKEN_HOST;
      }
      break;
    case 'y':
      if (memeq("var", name, 3)) {
        return NGHTTP2_HPACK_TOKEN_VARY;
      }
      break;
    }
    break;
  case 5:
    switch (name[4]) {
    case 'e':
      if (memeq("rang", name, 4)) {
        return NGHTTP2_HPACK_TOKEN_RANGE;
      }
      break;
    case 'h':
      if (memeq(":pat", name, 4)) {
        return NGHTTP2_HPACK_TOKEN__PATH;
      }
      break;
    case 'w':
      if (memeq("allo", name, 4)) {
        return NGHTTP2_HPACK_TOKEN_ALLOW;
      }
      break;
    }
    break;
  case 6:
    switch (name[5]) {
    case 'e':
      if (memeq("cooki", name, 5)) {
        return NGHTTP2_HPACK_TOKEN_COOKIE;
      }
      break;
    case 'r':
      if (memeq("serve", name, 5)) {
        return NGHTTP2_HPACK_TOKEN_SERVER;
      }
      break;
    case 't':
      if (memeq("accep", name, 5)) {
        return NGHTTP2_HPACK_TOKEN_ACCEPT;
      }
      if (memeq("expec", name, 5)) {
        return NGHTTP2_HPACK_TOKEN_EXPECT;
      }
      break;
    }
    break;
  case 7:
    switch (name[6]) {
    case 'd':
      if (memeq(":metho", name, 6)) {
        return NGHTTP2_HPACK_TOKEN__METHOD;
      }
      break;
    case 'e':
      if (memeq(":schem", name, 6)) {
        return NGHTTP2_HPACK_TOKEN__SCHEME;
      }
      if (memeq("upgrad", name, 6)) {
        return NGHTTP2_HPACK_TOKEN_UPGRADE;
      }
      break;
    case 'h':
      if (memeq("refres", name, 6)) {
        return NGHTTP2_HPACK_TOKEN_REFRESH;
      }
      break;
    case 'r':
      if (memeq("refere", name, 6)) {
        return NGHTTP2_HPACK_TOKEN_REFERER;
      }
      break;
    case 's':
      if (memeq(":statu", name, 6)) {
        return NGHTTP2_HPACK_TOKEN__STATUS;
      }
      if (memeq("expire", name, 6)) {
        return NGHTTP2_HPACK_TOKEN_EXPIRES;
      }
      break;
    }
    break;
  case 8:
    switch (name[7]) {
    case 'e':
      if (memeq("if-rang", name, 7)) {
        return NGHTTP2_HPACK_TOKEN_IF_RANGE;
      }
      break;
    case 'h':
      if (memeq("if-matc", name, 7)) {
        return NGHTTP2_HPACK_TOKEN_IF_MATCH;
      }
      break;
    case 'n':
      if (memeq("locatio", name, 7)) {
        return NGHTTP2_HPACK_TOKEN_LOCATION;
      }
      break;
    case 'y':
      if (memeq("priorit", name, 7)) {
        return NGHTTP2_HPACK_TOKEN_PRIORITY;
      }
      break;
    }
    break;
  case 9:
    switch (name[8]) {
    case 'l':
      if (memeq(":protoco", name, 8)) {
        return NGHTTP2_HPACK_TOKEN__PROTOCOL;
      }
      break;
    }
    break;
  case 10:
    switch (name[9]) {
    case 'e':
      if (memeq("keep-aliv", name, 9)) {
        return NGHTTP2_HPACK_TOKEN_KEEP_ALIVE;
      }
      if (memeq("set-cooki", name, 9)) {
        return NGHTTP2_HPACK_TOKEN_SET_COOKIE;
      }
      break;
    case 'n':
      if (memeq("connectio", name, 9)) {
        return NGHTTP2_HPACK_TOKEN_CONNECTION;
      }
      break;
    case 't':
      if (memeq("user-agen", name, 9)) {
        return NGHTTP2_HPACK_TOKEN_USER_AGENT;
      }
      break;
    case 'y':
      if (memeq(":authorit", name, 9)) {
        return NGHTTP2_HPACK_TOKEN__AUTHORITY;
      }
      break;
    }
    break;
  case 11:
    switch (name[10]) {
    case 'r':
      if (memeq("retry-afte", name, 10)) {
        return NGHTTP2_HPACK_TOKEN_RETRY_AFTER;
      }
      break;
    }
    break;
  case 12:
    switch (name[11]) {
    case 'e':
      if (memeq("content-typ", name, 11)) {
        return NGHTTP2_HPACK_TOKEN_CONTENT_TYPE;
      }
      break;
    case 's':
      if (memeq("max-forward", name, 11)) {
        return NGHTTP2_HPACK_TOKEN_MAX_FORWARDS;
      }
      break;
    }
    break;
  case 13:
    switch (name[12]) {
    case 'd':
      if (memeq("last-modifie", name, 12)) {
        return NGHTTP2_HPACK_TOKEN_LAST_MODIFIED;
      }
      break;
    case 'e':
      if (memeq("content-rang", name, 12)) {
        return NGHTTP2_HPACK_TOKEN_CONTENT_RANGE;
      }
      break;
    case 'h':
      if (memeq("if-none-matc", name, 12)) {
        return NGHTTP2_HPACK_TOKEN_IF_NONE_MATCH;
      }
      break;
    case 'l':
      if (memeq("cache-contro", name, 12)) {
        return NGHTTP2_HPACK_TOKEN_CACHE_CONTROL;
      }
      break;
    case 'n':
      if (memeq("authorizatio", name, 12)) {
        return NGHTTP2_HPACK_TOKEN_AUTHORIZATION;
      }
      break;
    case 's':
      if (memeq("accept-range", name, 12)) {
        return NGHTTP2_HPACK_TOKEN_ACCEPT_RANGES;
      }
      break;
    }
    break;
  case 14:
    switch (name[13]) {
    case 'h':
      if (memeq("content-lengt", name, 13)) {
        return NGHTTP2_HPACK_TOKEN_CONTENT_LENGTH;
      }
      break;
    case 't':
      if (memeq("accept-charse", name, 13)) {
        return NGHTTP2_HPACK_TOKEN_ACCEPT_CHARSET;
      }
      break;
    }
    break;
  case 15:
    switch (name[14]) {
    case 'e':
      if (memeq("accept-languag", name, 14)) {
        return NGHTTP2_HPACK_TOKEN_ACCEPT_LANGUAGE;
      }
      break;
    case 'g':
      if (memeq("accept-encodin", name, 14)) {
        return NGHTTP2_HPACK_TOKEN_ACCEPT_ENCODING;
      }
      break;
    }
    break;
  case 16:
    switch (name[15]) {
    case 'e':
      if (memeq("content-languag", name, 15)) {
        return NGHTTP2_HPACK_TOKEN_CONTENT_LANGUAGE;
      }
      if (memeq("www-authenticat", name, 15)) {
        return NGHTTP2_HPACK_TOKEN_WWW_AUTHENTICATE;
      }
      break;
    case 'g':
      if (memeq("content-encodin", name, 15)) {
        return NGHTTP2_HPACK_TOKEN_CONTENT_ENCODING;
      }
      break;
    case 'n':
      if (memeq("content-locatio", name, 15)) {
        return NGHTTP2_HPACK_TOKEN_CONTENT_LOCATION;
      }
      if (memeq("proxy-connectio", name, 15)) {
        return NGHTTP2_HPACK_TOKEN_PROXY_CONNECTION;
      }
      break;
    }
    break;
  case 17:
    switch (name[16]) {
    case 'e':
      if (memeq("if-modified-sinc", name, 16)) {
        return NGHTTP2_HPACK_TOKEN_IF_MODIFIED_SINCE;
      }
      break;
    case 'g':
      if (memeq("transfer-encodin", name, 16)) {
        return NGHTTP2_HPACK_TOKEN_TRANSFER_ENCODING;
      }
      break;
    }
    break;
  case 18:
    switch (name[17]) {
    case 'e':
      if (memeq("proxy-authenticat", name, 17)) {
        return NGHTTP2_HPACK_TOKEN_PROXY_AUTHENTICATE;
      }
      break;
    }
    break;
  case 19:
    switch (name[18]) {
    case 'e':
      if (memeq("if-unmodified-sinc", name, 18)) {
        return NGHTTP2_HPACK_TOKEN_IF_UNMODIFIED_SINCE;
      }
      break;
    case 'n':
      if (memeq("content-dispositio", name, 18)) {
        return NGHTTP2_HPACK_TOKEN_CONTENT_DISPOSITION;
      }
      if (memeq("proxy-authorizatio", name, 18)) {
        return NGHTTP2_HPACK_TOKEN_PROXY_AUTHORIZATION;
      }
      break;
    }
    break;
  case 25:
    switch (name[24]) {
    case 'y':
      if (memeq("strict-transport-securit", name, 24)) {
        return NGHTTP2_HPACK_TOKEN_STRICT_TRANSPORT_SECURITY;
      }
      break;
    }
    break;
  case 27:
    switch (name[26]) {
    case 'n':
      if (memeq("access-control-allow-origi", name, 26)) {
        return NGHTTP2_HPACK_TOKEN_ACCESS_CONTROL_ALLOW_ORIGIN;
      }
      break;
    }
    break;
  }
  return -1;
}

void nghttp2_hpack_entry_init(nghttp2_hpack_entry *ent,
                              const nghttp2_hpack_nv *nv, uint64_t seq,
                              uint32_t hash) {
  *ent = (nghttp2_hpack_entry){
    .nv = *nv,
    .seq = seq,
    .hash = hash,
  };

  nghttp2_rcbuf_incref(ent->nv.name);
  nghttp2_rcbuf_incref(ent->nv.value);
}

void nghttp2_hpack_entry_free(nghttp2_hpack_entry *ent) {
  nghttp2_rcbuf_decref(ent->nv.value);
  nghttp2_rcbuf_decref(ent->nv.name);
}

static int name_eq(const nghttp2_hpack_nv *a, const nghttp2_nv *b) {
  return a->name->len == b->namelen &&
         memeq(a->name->base, b->name, b->namelen);
}

static int value_eq(const nghttp2_hpack_nv *a, const nghttp2_nv *b) {
  return a->value->len == b->valuelen &&
         memeq(a->value->base, b->value, b->valuelen);
}

static uint32_t name_hash(const nghttp2_nv *nv) {
  /* 32 bit FNV-1a: http://isthe.com/chongo/tech/comp/fnv/ */
  uint32_t h = 2166136261u;
  size_t i;

  for (i = 0; i < nv->namelen; ++i) {
    h ^= nv->name[i];
    h += (h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24);
  }

  return h;
}

static void hpack_map_init(nghttp2_hpack_map *map) {
  *map = (nghttp2_hpack_map){0};
}

static void hpack_map_insert(nghttp2_hpack_map *map, nghttp2_hpack_entry *ent) {
  nghttp2_hpack_entry **bucket;

  bucket = &map->table[ent->hash & (HD_MAP_SIZE - 1)];

  if (*bucket == NULL) {
    *bucket = ent;
    return;
  }

  /* lower index is linked near the root */
  ent->next = *bucket;
  *bucket = ent;
}

static nghttp2_hpack_entry *hpack_map_find(const nghttp2_hpack_map *map,
                                           int *exact_match,
                                           const nghttp2_nv *nv, int32_t token,
                                           uint32_t hash, int name_only) {
  nghttp2_hpack_entry *p;
  nghttp2_hpack_entry *res = NULL;

  *exact_match = 0;

  for (p = map->table[hash & (HD_MAP_SIZE - 1)]; p; p = p->next) {
    if (token != p->nv.token ||
        (token == -1 && (hash != p->hash || !name_eq(&p->nv, nv)))) {
      continue;
    }

    if (!res) {
      res = p;

      if (name_only) {
        break;
      }
    }

    if (value_eq(&p->nv, nv)) {
      res = p;
      *exact_match = 1;

      break;
    }
  }

  return res;
}

static void hpack_map_remove(nghttp2_hpack_map *map, nghttp2_hpack_entry *ent) {
  nghttp2_hpack_entry **dst;

  dst = &map->table[ent->hash & (HD_MAP_SIZE - 1)];

  for (; *dst; dst = &(*dst)->next) {
    if (*dst != ent) {
      continue;
    }

    *dst = ent->next;
    ent->next = NULL;

    return;
  }
}

static void hpack_context_init(nghttp2_hpack_context *ctx,
                               size_t hard_max_dtable_capacity,
                               const nghttp2_mem *mem) {
  nghttp2_ringbuf_init(&ctx->dtable, 0, sizeof(nghttp2_hpack_entry *), mem);

  ctx->mem = mem;
  ctx->bad = 0;
  ctx->hard_max_dtable_capacity = hard_max_dtable_capacity;
  ctx->max_dtable_capacity = NGHTTP2_HPACK_DEFAULT_DTABLE_CAPACITY;
  ctx->dtable_size = 0;
  ctx->next_seq = 0;
}

static void hpack_context_free(nghttp2_hpack_context *ctx) {
  nghttp2_hpack_entry *ent;
  size_t i, len = nghttp2_ringbuf_len(&ctx->dtable);

  for (i = 0; i < len; ++i) {
    ent = *(nghttp2_hpack_entry **)nghttp2_ringbuf_get(&ctx->dtable, i);

    nghttp2_hpack_entry_free(ent);
    nghttp2_mem_free(ctx->mem, ent);
  }

  nghttp2_ringbuf_free(&ctx->dtable);
}

void nghttp2_hpack_encoder_init(nghttp2_hpack_encoder *encoder,
                                size_t hard_max_dtable_capacity,
                                const nghttp2_mem *mem) {
  hpack_context_init(&encoder->ctx, hard_max_dtable_capacity, mem);
  hpack_map_init(&encoder->map);

  if (hard_max_dtable_capacity < NGHTTP2_HPACK_DEFAULT_DTABLE_CAPACITY) {
    encoder->notify_table_size_change = 1;
    encoder->ctx.max_dtable_capacity = hard_max_dtable_capacity;
  } else {
    encoder->notify_table_size_change = 0;
  }

  encoder->min_dtable_capacity = UINT32_MAX;
}

void nghttp2_hpack_encoder_free(nghttp2_hpack_encoder *encoder) {
  if (!encoder) {
    return;
  }

  hpack_context_free(&encoder->ctx);
}

void nghttp2_hpack_decoder_init(nghttp2_hpack_decoder *decoder,
                                const nghttp2_mem *mem) {
  hpack_context_init(&decoder->ctx, NGHTTP2_HPACK_DEFAULT_DTABLE_CAPACITY, mem);

  decoder->min_dtable_capacity = UINT32_MAX;
  decoder->opcode = NGHTTP2_HPACK_OPCODE_NONE;
  decoder->state = NGHTTP2_HPACK_STATE_START;

  nghttp2_hpack_read_state_reset(&decoder->rstate);
}

void nghttp2_hpack_decoder_free(nghttp2_hpack_decoder *decoder) {
  if (!decoder) {
    return;
  }

  nghttp2_hpack_read_state_free(&decoder->rstate);
  hpack_context_free(&decoder->ctx);
}

static size_t entry_room(size_t namelen, size_t valuelen) {
  return NGHTTP2_HPACK_ENTRY_OVERHEAD + namelen + valuelen;
}

static void emit_header(nghttp2_hpack_nv *dest, const nghttp2_hpack_nv *nv) {
  DEBUGF("decode: header emission: %s: %s\n", nv->name->base, nv->value->base);
  /* ent->ref may be 0. This happens if the encoder emits literal
     block larger than header table capacity with indexing. */
  *dest = *nv;
}

static size_t count_encoded_length(size_t n, size_t prefix) {
  size_t k = (size_t)((1 << prefix) - 1);
  size_t len = 0;

  if (n < k) {
    return 1;
  }

  n -= k;
  ++len;

  for (; n >= 128; n >>= 7, ++len)
    ;

  return len + 1;
}

static uint8_t *encode_length(uint8_t *dest, size_t n, size_t prefix) {
  size_t k = (size_t)((1 << prefix) - 1);

  *dest = (uint8_t)(*dest & ~k);

  if (n < k) {
    *dest = (uint8_t)(*dest | n);
    ++dest;

    return dest;
  }

  *dest = (uint8_t)(*dest | k);
  ++dest;

  n -= k;

  for (; n >= 128; n >>= 7) {
    *dest++ = (uint8_t)((1 << 7) | (n & 0x7F));
  }

  *dest++ = (uint8_t)n;

  return dest;
}

/*
 * Decodes |prefix| prefixed integer stored from |in|.  The |last|
 * represents the 1 beyond the last of the valid contiguous memory
 * region from |in|.  The decoded integer must be less than or equal
 * to UINT32_MAX.
 *
 * If the |initial| is nonzero, it is used as a initial value, this
 * function assumes the |in| starts with intermediate data.
 *
 * An entire integer is decoded successfully, decoded, the |*pfin| is
 * set to nonzero.
 *
 * This function stores the decoded integer in |*dest| if it succeed,
 * including partial decoding (in this case, number of shift to make
 * in the next call will be stored in |*pshift|) and returns number of
 * bytes processed, or returns -1, indicating decoding error.
 */
static nghttp2_ssize decode_length(uint32_t *dest, size_t *pshift, int *pfin,
                                   uint32_t initial, size_t shift,
                                   const uint8_t *first, const uint8_t *last,
                                   size_t prefix) {
  uint32_t k = (uint8_t)((1 << prefix) - 1);
  uint32_t n = initial;
  uint32_t add;
  const uint8_t *p = first;

  *pshift = 0;
  *pfin = 0;

  if (n == 0) {
    if ((*p & k) != k) {
      *dest = (*p) & k;
      *pfin = 1;

      return 1;
    }

    n = k;

    if (++p == last) {
      *dest = n;
      return p - first;
    }
  }

  for (; p != last; ++p, shift += 7) {
    add = *p & 0x7F;

    if (shift >= 32) {
      DEBUGF("decode: shift exponent overflow\n");
      return -1;
    }

    if ((UINT32_MAX >> shift) < add) {
      DEBUGF("decode: integer overflow on shift\n");
      return -1;
    }

    add <<= shift;

    if (UINT32_MAX - add < n) {
      DEBUGF("decode: integer overflow on addition\n");
      return -1;
    }

    n += add;

    if ((*p & (1 << 7)) == 0) {
      break;
    }
  }

  *pshift = shift;

  if (p == last) {
    *dest = n;
    return p - first;
  }

  *dest = n;
  *pfin = 1;

  return p + 1 - first;
}

/*
 * reserve_buf ensures that |buf| contains at least |extra_size| of
 * free space.  In other words, if this function succeeds,
 * nghttp2_buf_left(buf) >= extra_size holds.
 *
 * This function returns 0 if it succeeds, or one of the following
 * negative error codes:
 *
 * NGHTTP2_ERR_NOMEM
 *     Out of memory.
 */
static int reserve_buf(nghttp2_buf *buf, size_t extra_size,
                       const nghttp2_mem *mem) {
  size_t left = nghttp2_buf_left(buf);
  size_t n = 32;

  if (left >= extra_size) {
    return 0;
  }

  n = nghttp2_max(n, nghttp2_buf_cap(buf) + extra_size - left);

  /* Check whether we are requesting too much memory */
  if (n > (1U << 31)) {
    return NGHTTP2_ERR_NOMEM;
  }

#ifndef WIN32
  n = 1U << (32 - __builtin_clz((uint32_t)n - 1));
#else  /* defined(WIN32) */
  /* Round up to the next highest power of 2 from Bit Twiddling
     Hacks */
  --n;
  n |= n >> 1;
  n |= n >> 2;
  n |= n >> 4;
  n |= n >> 8;
  n |= n >> 16;
  ++n;
#endif /* defined(WIN32) */

  return nghttp2_buf_reserve(buf, n, mem);
}

static int hpack_encoder_write_table_size(nghttp2_hpack_encoder *encoder,
                                          nghttp2_buf *buf, size_t table_size) {
  int rv;

  DEBUGF("encoder: emit table_size=%zu\n", table_size);

  rv = reserve_buf(buf, count_encoded_length(table_size, 5), encoder->ctx.mem);
  if (rv != 0) {
    return rv;
  }

  *buf->last = 0x20U;
  buf->last = encode_length(buf->last, table_size, 5);

  return 0;
}

static int hpack_encoder_write_indexed(nghttp2_hpack_encoder *encoder,
                                       nghttp2_buf *buf, size_t idx) {
  int rv;
  size_t blocklen;

  blocklen = count_encoded_length(idx + 1, 7);

  DEBUGF("encoder: emit indexed index=%zu, %zu bytes\n", idx, blocklen);

  rv = reserve_buf(buf, blocklen, encoder->ctx.mem);
  if (rv != 0) {
    return rv;
  }

  *buf->last = 0x80U;
  buf->last = encode_length(buf->last, idx + 1, 7);

  return 0;
}

static int hpack_encoder_write_string(nghttp2_hpack_encoder *encoder,
                                      nghttp2_buf *buf, const uint8_t *str,
                                      size_t len) {
  int rv;
  uint8_t *p;
  size_t blocklen;
  size_t enclen;
  int huffman = 0;

  enclen = nghttp2_hpack_huffman_encode_count(str, len);
  if (enclen < len) {
    huffman = 1;
  } else {
    enclen = len;
  }

  blocklen = count_encoded_length(enclen, 7);

  DEBUGF("encoder: emit string str=%.*s, length=%zu, huffman=%d, "
         "encoded_length=%zu\n",
         (int)len, (const char *)str, len, huffman, enclen);

  rv = reserve_buf(buf, blocklen + enclen, encoder->ctx.mem);
  if (rv != 0) {
    return rv;
  }

  p = buf->last;
  *p = huffman ? 1 << 7 : 0;
  p = encode_length(p, enclen, 7);

  if (huffman) {
    p = nghttp2_hpack_huffman_encode(p, str, len);
  } else {
    assert(enclen == len);

    p = nghttp2_cpymem(p, str, len);
  }

  buf->last = p;

  return 0;
}

static uint8_t pack_first_byte(int indexing_mode) {
  switch (indexing_mode) {
  case NGHTTP2_HPACK_WITH_INDEXING:
    return 0x40U;
  case NGHTTP2_HPACK_WITHOUT_INDEXING:
    return 0;
  case NGHTTP2_HPACK_NEVER_INDEXING:
    return 0x10U;
  default:
    assert(0);
  }

  /* This is required to compile with android NDK r10d +
     --enable-werror */
  return 0;
}

static int hpack_encoder_write_indname(nghttp2_hpack_encoder *encoder,
                                       nghttp2_buf *buf, size_t idx,
                                       const nghttp2_nv *nv,
                                       int indexing_mode) {
  int rv;
  size_t prefixlen;

  if (indexing_mode == NGHTTP2_HPACK_WITH_INDEXING) {
    prefixlen = 6;
  } else {
    prefixlen = 4;
  }

  DEBUGF("encoder: emit indname index=%zu, valuelen=%zu, indexing_mode=%d\n",
         idx, nv->valuelen, indexing_mode);

  rv = reserve_buf(buf, count_encoded_length(idx + 1, prefixlen),
                   encoder->ctx.mem);
  if (rv != 0) {
    return rv;
  }

  *buf->last = pack_first_byte(indexing_mode);
  buf->last = encode_length(buf->last, idx + 1, prefixlen);

  return hpack_encoder_write_string(encoder, buf, nv->value, nv->valuelen);
}

static int hpack_encoder_write_newname(nghttp2_hpack_encoder *encoder,
                                       nghttp2_buf *buf, const nghttp2_nv *nv,
                                       int indexing_mode) {
  int rv;

  DEBUGF("encoder: emit newname namelen=%zu, valuelen=%zu, indexing_mode=%d\n",
         nv->namelen, nv->valuelen, indexing_mode);

  rv = reserve_buf(buf, 1, encoder->ctx.mem);
  if (rv != 0) {
    return rv;
  }

  *buf->last++ = pack_first_byte(indexing_mode);

  rv = hpack_encoder_write_string(encoder, buf, nv->name, nv->namelen);
  if (rv != 0) {
    return rv;
  }

  return hpack_encoder_write_string(encoder, buf, nv->value, nv->valuelen);
}

static int hpack_context_add_dtable(nghttp2_hpack_context *ctx,
                                    nghttp2_hpack_nv *nv,
                                    nghttp2_hpack_map *map, uint32_t hash) {
  int rv;
  size_t i;
  nghttp2_hpack_entry *ent, *new_ent;
  size_t room = entry_room(nv->name->len, nv->value->len);
  const nghttp2_mem *mem = ctx->mem;

  while (ctx->dtable_size + room > ctx->max_dtable_capacity &&
         nghttp2_ringbuf_len(&ctx->dtable)) {
    i = nghttp2_ringbuf_len(&ctx->dtable);
    ent = *(nghttp2_hpack_entry **)nghttp2_ringbuf_get(&ctx->dtable, i - 1);

    ctx->dtable_size -= entry_room(ent->nv.name->len, ent->nv.value->len);

    DEBUGF("hpack: remove item from header table: %s: %s\n",
           (char *)ent->nv.name->base, (char *)ent->nv.value->base);

    nghttp2_ringbuf_pop_back(&ctx->dtable);

    if (map) {
      hpack_map_remove(map, ent);
    }

    nghttp2_hpack_entry_free(ent);
    nghttp2_mem_free(mem, ent);
  }

  if (room > ctx->max_dtable_capacity) {
    /* The entry taking more than NGHTTP2_HPACK_MAX_BUFFER_SIZE is
       immediately evicted.  So we don't allocate memory for it. */
    return 0;
  }

  new_ent = nghttp2_mem_malloc(mem, sizeof(nghttp2_hpack_entry));
  if (new_ent == NULL) {
    return NGHTTP2_ERR_NOMEM;
  }

  nghttp2_hpack_entry_init(new_ent, nv, ctx->next_seq++, hash);

  if (nghttp2_ringbuf_full(&ctx->dtable)) {
    rv = nghttp2_ringbuf_reserve(
      &ctx->dtable, nghttp2_max(128, nghttp2_ringbuf_len(&ctx->dtable) * 2));
    if (rv != 0) {
      nghttp2_hpack_entry_free(new_ent);
      nghttp2_mem_free(mem, new_ent);

      return rv;
    }
  }

  *(nghttp2_hpack_entry **)nghttp2_ringbuf_push_front(&ctx->dtable) = new_ent;

  if (map) {
    hpack_map_insert(map, new_ent);
  }

  ctx->dtable_size += room;

  return 0;
}

typedef struct {
  nghttp2_ssize index;
  /* Nonzero if both name and value are matched. */
  int name_value_match;
} search_result;

static search_result search_static_table(const nghttp2_nv *nv, int32_t token,
                                         int name_only) {
  search_result res = {
    .index = token,
  };
  int i;
  const nghttp2_hpack_static_entry *ent;

  if (name_only) {
    return res;
  }

  for (i = token; i <= NGHTTP2_HPACK_TOKEN_WWW_AUTHENTICATE &&
                  static_table[i].nv.token == token;
       ++i) {
    ent = &static_table[i];
    if (ent->nv.value->len == nv->valuelen &&
        memcmp(ent->nv.value->base, nv->value, nv->valuelen) == 0) {
      res = (search_result){
        .index = i,
        .name_value_match = 1,
      };

      return res;
    }
  }

  return res;
}

static search_result hpack_context_search_dtable(
  const nghttp2_hpack_context *ctx, const nghttp2_nv *nv, int32_t token,
  int indexing_mode, nghttp2_hpack_map *map, uint32_t hash) {
  search_result res = {
    .index = -1,
  };
  const nghttp2_hpack_entry *ent;
  int exact_match;
  int name_only = indexing_mode == NGHTTP2_HPACK_NEVER_INDEXING;

  exact_match = 0;
  ent = hpack_map_find(map, &exact_match, nv, token, hash, name_only);

  if (!exact_match && token >= 0 &&
      token <= NGHTTP2_HPACK_TOKEN_WWW_AUTHENTICATE) {
    return search_static_table(nv, token, name_only);
  }

  if (ent == NULL) {
    return res;
  }

  res = (search_result){
    .index = (nghttp2_ssize)(ctx->next_seq - 1 - ent->seq +
                             NGHTTP2_STATIC_TABLE_LENGTH),
    .name_value_match = exact_match,
  };

  return res;
}

static void hpack_context_shrink_table_size(nghttp2_hpack_context *ctx,
                                            nghttp2_hpack_map *map) {
  const nghttp2_mem *mem = ctx->mem;
  nghttp2_hpack_entry *ent;
  size_t i;

  while (ctx->dtable_size > ctx->max_dtable_capacity &&
         nghttp2_ringbuf_len(&ctx->dtable)) {
    i = nghttp2_ringbuf_len(&ctx->dtable);
    ent = *(nghttp2_hpack_entry **)nghttp2_ringbuf_get(&ctx->dtable, i - 1);
    ctx->dtable_size -= entry_room(ent->nv.name->len, ent->nv.value->len);
    nghttp2_ringbuf_pop_back(&ctx->dtable);

    if (map) {
      hpack_map_remove(map, ent);
    }

    nghttp2_hpack_entry_free(ent);
    nghttp2_mem_free(mem, ent);
  }
}

void nghttp2_hpack_encoder_set_max_dtable_capacity(
  nghttp2_hpack_encoder *encoder, size_t max_dtable_capacity) {
  max_dtable_capacity =
    nghttp2_min(max_dtable_capacity, encoder->ctx.hard_max_dtable_capacity);

  encoder->ctx.max_dtable_capacity = max_dtable_capacity;
  encoder->min_dtable_capacity =
    nghttp2_min(encoder->min_dtable_capacity, max_dtable_capacity);
  encoder->notify_table_size_change = 1;

  hpack_context_shrink_table_size(&encoder->ctx, &encoder->map);
}

int nghttp2_hpack_decoder_set_max_dtable_capacity(
  nghttp2_hpack_decoder *decoder, size_t max_dtable_capacity) {
  switch (decoder->state) {
  case NGHTTP2_HPACK_STATE_EXPECT_TABLE_SIZE:
  case NGHTTP2_HPACK_STATE_START:
    break;
  default:
    return NGHTTP2_ERR_INVALID_STATE;
  }

  decoder->ctx.hard_max_dtable_capacity = max_dtable_capacity;

  /* It seems that encoder is not required to send dynamic table size
     update if the table size is not changed after applying
     SETTINGS_HEADER_TABLE_SIZE.  RFC 7541 is ambiguous here, but this
     is the intention of the editor.  If new maximum table size is
     strictly smaller than the current negotiated maximum size,
     encoder must send dynamic table size update.  In other cases, we
     cannot expect it to do so. */
  if (decoder->ctx.max_dtable_capacity > max_dtable_capacity) {
    decoder->state = NGHTTP2_HPACK_STATE_EXPECT_TABLE_SIZE;
    /* Remember minimum value, and validate that encoder sends the
       value less than or equal to this. */
    decoder->min_dtable_capacity = max_dtable_capacity;
    decoder->ctx.max_dtable_capacity = max_dtable_capacity;

    hpack_context_shrink_table_size(&decoder->ctx, NULL);
  }

  return 0;
}

#define INDEX_RANGE_VALID(ctx, idx)                                            \
  ((idx) < (ctx)->dtable.len + NGHTTP2_STATIC_TABLE_LENGTH)

static size_t hpack_context_get_max_index(const nghttp2_hpack_context *ctx) {
  return nghttp2_ringbuf_len(&ctx->dtable) + NGHTTP2_STATIC_TABLE_LENGTH;
}

const nghttp2_hpack_nv *
nghttp2_hpack_context_table_get(const nghttp2_hpack_context *ctx, size_t idx) {
  assert(INDEX_RANGE_VALID(ctx, idx));

  if (idx >= NGHTTP2_STATIC_TABLE_LENGTH) {
    return &(*(nghttp2_hpack_entry **)nghttp2_ringbuf_get(
               (nghttp2_ringbuf *)&ctx->dtable,
               idx - NGHTTP2_STATIC_TABLE_LENGTH))
              ->nv;
  }

  return &static_table[idx].nv;
}

static int hpack_encoder_decide_indexing(const nghttp2_hpack_encoder *encoder,
                                         const nghttp2_nv *nv, int32_t token) {
  if (token == NGHTTP2_HPACK_TOKEN__PATH || token == NGHTTP2_HPACK_TOKEN_AGE ||
      token == NGHTTP2_HPACK_TOKEN_CONTENT_LENGTH ||
      token == NGHTTP2_HPACK_TOKEN_ETAG ||
      token == NGHTTP2_HPACK_TOKEN_IF_MODIFIED_SINCE ||
      token == NGHTTP2_HPACK_TOKEN_IF_NONE_MATCH ||
      token == NGHTTP2_HPACK_TOKEN_LOCATION ||
      token == NGHTTP2_HPACK_TOKEN_SET_COOKIE ||
      entry_room(nv->namelen, nv->valuelen) >
        encoder->ctx.max_dtable_capacity * 3 / 4) {
    return NGHTTP2_HPACK_WITHOUT_INDEXING;
  }

  return NGHTTP2_HPACK_WITH_INDEXING;
}

static int hpack_encoder_write(nghttp2_hpack_encoder *encoder, nghttp2_buf *buf,
                               const nghttp2_nv *nv) {
  int rv;
  search_result res;
  nghttp2_ssize idx;
  int indexing_mode;
  int32_t token;
  const nghttp2_mem *mem = encoder->ctx.mem;
  uint32_t hash = 0;
  nghttp2_hpack_nv hnv;

  DEBUGF("encoder: deflating %.*s: %.*s\n", (int)nv->namelen, nv->name,
         (int)nv->valuelen, nv->value);

  token = lookup_token(nv->name, nv->namelen);
  if (token == -1) {
    hash = name_hash(nv);
  } else if (token <= NGHTTP2_HPACK_TOKEN_WWW_AUTHENTICATE) {
    hash = static_table[token].hash;
  }

  /* Do not index authorization header field since it may contain low
     entropy secret data (e.g., ID/password).  Also cookie header
     field with less than 20 bytes value is also never indexed.  This
     is the same criteria used in Firefox codebase. */
  indexing_mode =
    token == NGHTTP2_HPACK_TOKEN_AUTHORIZATION ||
        (token == NGHTTP2_HPACK_TOKEN_COOKIE && nv->valuelen < 20) ||
        (nv->flags & NGHTTP2_NV_FLAG_NEVER_INDEX)
      ? NGHTTP2_HPACK_NEVER_INDEXING
      : hpack_encoder_decide_indexing(encoder, nv, token);

  res = hpack_context_search_dtable(&encoder->ctx, nv, token, indexing_mode,
                                    &encoder->map, hash);

  idx = res.index;

  if (res.name_value_match) {
    DEBUGF("encoder: name/value match index=%td\n", idx);

    return hpack_encoder_write_indexed(encoder, buf, (size_t)idx);
  }

  if (res.index != -1) {
    DEBUGF("encoder: name match index=%td\n", res.index);
  }

  if (indexing_mode == NGHTTP2_HPACK_WITH_INDEXING) {
    if (idx != -1) {
      hnv.name =
        nghttp2_hpack_context_table_get(&encoder->ctx, (size_t)idx)->name;
      nghttp2_rcbuf_incref(hnv.name);
    } else {
      rv = nghttp2_rcbuf_new2(&hnv.name, nv->name, nv->namelen, mem);
      if (rv != 0) {
        return rv;
      }
    }

    rv = nghttp2_rcbuf_new2(&hnv.value, nv->value, nv->valuelen, mem);
    if (rv != 0) {
      nghttp2_rcbuf_decref(hnv.name);
      return rv;
    }

    hnv.token = token;
    hnv.flags = NGHTTP2_NV_FLAG_NONE;

    rv = hpack_context_add_dtable(&encoder->ctx, &hnv, &encoder->map, hash);

    nghttp2_rcbuf_decref(hnv.value);
    nghttp2_rcbuf_decref(hnv.name);

    if (rv != 0) {
      return NGHTTP2_ERR_HPACK_FATAL;
    }
  }

  if (idx == -1) {
    return hpack_encoder_write_newname(encoder, buf, nv, indexing_mode);
  }

  return hpack_encoder_write_indname(encoder, buf, (size_t)idx, nv,
                                     indexing_mode);
}

int nghttp2_hpack_encoder_write(nghttp2_hpack_encoder *encoder,
                                nghttp2_buf *buf, const nghttp2_nv *nv,
                                size_t nvlen) {
  size_t i;
  int rv = 0;
  size_t min_dtable_capacity;

  if (encoder->ctx.bad) {
    return NGHTTP2_ERR_HPACK_FATAL;
  }

  if (encoder->notify_table_size_change) {
    min_dtable_capacity = encoder->min_dtable_capacity;

    encoder->notify_table_size_change = 0;
    encoder->min_dtable_capacity = UINT32_MAX;

    if (encoder->ctx.max_dtable_capacity > min_dtable_capacity) {
      rv = hpack_encoder_write_table_size(encoder, buf, min_dtable_capacity);
      if (rv != 0) {
        goto fail;
      }
    }

    rv = hpack_encoder_write_table_size(encoder, buf,
                                        encoder->ctx.max_dtable_capacity);
    if (rv != 0) {
      goto fail;
    }
  }

  for (i = 0; i < nvlen; ++i) {
    rv = hpack_encoder_write(encoder, buf, &nv[i]);
    if (rv != 0) {
      goto fail;
    }
  }

  DEBUGF("encoder: all input name/value pairs were encoded\n");

  return 0;

fail:
  DEBUGF("encoder: error return %d\n", rv);

  encoder->ctx.bad = 1;

  return rv;
}

size_t nghttp2_hpack_bound(const nghttp2_nv *nva, size_t nvlen) {
  size_t n = 0;
  size_t i;

  /* Possible Maximum Header Table Size Change.  Encoding (1u << 31) -
     1 using 4 bit prefix requires 6 bytes.  We may emit this at most
     twice. */
  n += 12;

  /* Use Literal Header Field without indexing - New Name, since it is
     most space consuming format.  Also we choose the less one between
     non-huffman and huffman, so using literal byte count is
     sufficient for upper bound.

     Encoding (1u << 31) - 1 using 7 bit prefix requires 6 bytes.  We
     need 2 of this for |nvlen| header fields. */
  n += 6 * 2 * nvlen;

  for (i = 0; i < nvlen; ++i) {
    n += nva[i].namelen + nva[i].valuelen;
  }

  return n;
}

static void hpack_decoder_set_huffman_encoded(nghttp2_hpack_decoder *decoder,
                                              const uint8_t *src) {
  decoder->rstate.huffman_encoded = (*src & (1 << 7)) != 0;
}

/*
 * Decodes the integer from the range [in, last).  The result is
 * assigned to |decoder->rstate.left|.  If the |decoder->rstate.left|
 * is 0, then it performs variable integer decoding from scratch.
 * Otherwise, it uses the |decoder->rstate.left| as the initial value
 * and continues to decode assuming that [in, last) begins with
 * intermediary sequence.
 *
 * This function returns the number of bytes read if it succeeds, or
 * one of the following negative error codes:
 *
 * NGHTTP2_ERR_HPACK_FATAL
 *   Integer decoding failed
 */
static nghttp2_ssize hpack_decoder_read_len(nghttp2_hpack_decoder *decoder,
                                            int *pfin, const uint8_t *first,
                                            const uint8_t *last, size_t prefix,
                                            size_t maxlen) {
  nghttp2_ssize nread;
  uint32_t len;

  *pfin = 0;

  nread = decode_length(&len, &decoder->rstate.shift, pfin,
                        (uint32_t)decoder->rstate.left, decoder->rstate.shift,
                        first, last, prefix);
  if (nread < 0) {
    DEBUGF("decoder: integer decoding failed\n");
    return NGHTTP2_ERR_HPACK_FATAL;
  }

  if (len > maxlen) {
    DEBUGF("decoder: integer exceeded the maximum value %zu\n", maxlen);
    return NGHTTP2_ERR_HPACK_FATAL;
  }

  decoder->rstate.left = len;

  DEBUGF("decoder: decoded integer is %u\n", len);

  return nread;
}

/*
 * Reads |decoder->rstate.left| bytes from the range [first, last) and
 * performs huffman decoding against them and pushes the result into
 * the |buf|.
 *
 * This function returns the number of bytes read if it succeeds, or
 * one of the following negative error codes:
 *
 * NGHTTP2_ERR_NOMEM
 *   Out of memory
 * NGHTTP2_ERR_HPACK_FATAL
 *   Huffman decoding failed
 */
static nghttp2_ssize
hpack_decoder_read_huffman_string(nghttp2_hpack_decoder *decoder,
                                  nghttp2_buf *buf, const uint8_t *first,
                                  const uint8_t *last) {
  nghttp2_ssize nwrite;
  int fin = 0;
  size_t len = (size_t)(last - first);

  if (len >= decoder->rstate.left) {
    len = decoder->rstate.left;
    fin = 1;
  }

  nwrite = nghttp2_hpack_huffman_decode(&decoder->rstate.huffman_ctx, buf->last,
                                        first, len, fin);
  if (nwrite < 0) {
    DEBUGF("decoder: huffman decoding failed\n");
    return nwrite;
  }

  if (nghttp2_hpack_huffman_decode_failure_state(
        &decoder->rstate.huffman_ctx)) {
    DEBUGF("decoder: huffman decoding failed\n");
    return NGHTTP2_ERR_HPACK_FATAL;
  }

  buf->last += nwrite;
  decoder->rstate.left -= len;

  return (nghttp2_ssize)len;
}

/*
 * Reads |decoder|->rstate.left bytes from the range [first, last) at
 * most |decoder|->rstate.left if the range is larger and copies them
 * into the |buf|.
 *
 * This function returns the number of bytes read if it succeeds, or
 * one of the following negative error codes:
 *
 * NGHTTP2_ERR_NOMEM
 *   Out of memory
 * NGHTTP2_ERR_HPACK_FATAL
 *   Header decompression failed
 */
static nghttp2_ssize hpack_decoder_read_string(nghttp2_hpack_decoder *decoder,
                                               nghttp2_buf *buf,
                                               const uint8_t *first,
                                               const uint8_t *last) {
  size_t len = nghttp2_min((size_t)(last - first), decoder->rstate.left);

  buf->last = nghttp2_cpymem(buf->last, first, len);

  decoder->rstate.left -= len;

  return (nghttp2_ssize)len;
}

/*
 * Finalize indexed header representation reception.  The referenced
 * header is always emitted, and |*dest| is filled with that value.
 */
static void hpack_decoder_emit_indexed(nghttp2_hpack_decoder *decoder,
                                       nghttp2_hpack_nv *dest) {
  const nghttp2_hpack_nv *nv =
    nghttp2_hpack_context_table_get(&decoder->ctx, decoder->rstate.index);

  emit_header(dest, nv);

  nghttp2_rcbuf_incref(dest->name);
  nghttp2_rcbuf_incref(dest->value);
}

/*
 * Finalize literal header representation - new name- reception. If
 * header is emitted, |*dest| is filled with that value and 0 is
 * returned.
 *
 * This function returns 0 if it succeeds, or one of the following
 * negative error codes:
 *
 * NGHTTP2_ERR_NOMEM
 *   Out of memory
 */
static int hpack_decoder_emit_newname(nghttp2_hpack_decoder *decoder,
                                      nghttp2_hpack_nv *dest) {
  nghttp2_hpack_nv nv;
  int rv;

  if (decoder->rstate.never) {
    nv.flags = NGHTTP2_NV_FLAG_NEVER_INDEX;
  } else {
    nv.flags = NGHTTP2_NV_FLAG_NONE;
  }

  nv.name = decoder->rstate.name;
  nv.value = decoder->rstate.value;
  nv.token =
    lookup_token(decoder->rstate.name->base, decoder->rstate.name->len);

  if (decoder->rstate.indexing) {
    rv = hpack_context_add_dtable(&decoder->ctx, &nv, NULL, 0);
    if (rv != 0) {
      return rv;
    }
  }

  emit_header(dest, &nv);

  decoder->rstate.name = NULL;
  decoder->rstate.value = NULL;

  return 0;
}

/*
 * Finalize literal header representation - indexed name-
 * reception. If header is emitted, |*dest| is filled with that value
 * and 0 is returned.
 *
 * This function returns 0 if it succeeds, or one of the following
 * negative error codes:
 *
 * NGHTTP2_ERR_NOMEM
 *   Out of memory
 */
static int hpack_decoder_emit_indname(nghttp2_hpack_decoder *decoder,
                                      nghttp2_hpack_nv *dest) {
  nghttp2_hpack_nv nv;
  int rv;

  nv = *nghttp2_hpack_context_table_get(&decoder->ctx, decoder->rstate.index);

  if (decoder->rstate.never) {
    nv.flags = NGHTTP2_NV_FLAG_NEVER_INDEX;
  } else {
    nv.flags = NGHTTP2_NV_FLAG_NONE;
  }

  nghttp2_rcbuf_incref(nv.name);

  nv.value = decoder->rstate.value;

  if (decoder->rstate.indexing) {
    rv = hpack_context_add_dtable(&decoder->ctx, &nv, NULL, 0);
    if (rv != 0) {
      nghttp2_rcbuf_decref(nv.name);
      return NGHTTP2_ERR_NOMEM;
    }
  }

  emit_header(dest, &nv);

  decoder->rstate.value = NULL;

  return 0;
}

nghttp2_ssize nghttp2_hpack_decoder_read(nghttp2_hpack_decoder *decoder,
                                         nghttp2_hpack_nv *dest,
                                         uint8_t *pflags, const uint8_t *src,
                                         size_t srclen, int fin) {
  const uint8_t *p = src, *last = src ? src + srclen : src;
  int rfin;
  int busy = 0;
  const nghttp2_mem *mem = decoder->ctx.mem;
  nghttp2_hpack_read_state *rstate = &decoder->rstate;
  nghttp2_ssize nread;
  int rv;

  if (decoder->ctx.bad) {
    return NGHTTP2_ERR_HPACK_FATAL;
  }

  DEBUGF("decoder: start state=%d\n", decoder->state);

  *pflags = NGHTTP2_HPACK_DECODE_FLAG_NONE;

  for (; p != last || busy;) {
    busy = 0;

    switch (decoder->state) {
    case NGHTTP2_HPACK_STATE_EXPECT_TABLE_SIZE:
      if ((*p & 0xE0U) != 0x20U) {
        DEBUGF("decoder: header table size change was expected, but saw "
               "0x%02x as first byte",
               *p);

        rv = NGHTTP2_ERR_HPACK_FATAL;

        goto fail;
      }
    /* fall through */
    case NGHTTP2_HPACK_STATE_START:
    case NGHTTP2_HPACK_STATE_OPCODE:
      switch (*p >> 4) {
      case 0x0U:
        DEBUGF("decoder: literal header field without indexing\n");

        if (*p == 0x00U) {
          decoder->opcode = NGHTTP2_HPACK_OPCODE_NEWNAME;
          decoder->state = NGHTTP2_HPACK_STATE_NEWNAME_CHECK_NAMELEN;
          ++p;
        } else {
          decoder->opcode = NGHTTP2_HPACK_OPCODE_INDNAME;
          decoder->state = NGHTTP2_HPACK_STATE_READ_INDEX;
          rstate->prefix = 4;
        }

        rstate->indexing = 0;
        rstate->never = 0;

        break;
      case 0x1U:
        DEBUGF("decoder: literal header field never indexed\n");

        if (*p == 0x10U) {
          decoder->opcode = NGHTTP2_HPACK_OPCODE_NEWNAME;
          decoder->state = NGHTTP2_HPACK_STATE_NEWNAME_CHECK_NAMELEN;
          ++p;
        } else {
          decoder->opcode = NGHTTP2_HPACK_OPCODE_INDNAME;
          decoder->state = NGHTTP2_HPACK_STATE_READ_INDEX;
          rstate->prefix = 4;
        }

        rstate->indexing = 0;
        rstate->never = 1;

        break;
      case 0x2U:
      case 0x3U:
        DEBUGF("decoder: dynamic table size update\n");

        if (decoder->state == NGHTTP2_HPACK_STATE_OPCODE) {
          DEBUGF("decoder: header table size change must appear at the head "
                 "of header block\n");

          rv = NGHTTP2_ERR_HPACK_FATAL;

          goto fail;
        }

        decoder->opcode = NGHTTP2_HPACK_OPCODE_INDEXED;
        decoder->state = NGHTTP2_HPACK_STATE_READ_TABLE_SIZE;

        break;
      case 0x4U:
      case 0x5U:
      case 0x6U:
      case 0x7U:
        DEBUGF("decoder: literal header field with incremental indexing");

        if (*p == 0x40U) {
          decoder->opcode = NGHTTP2_HPACK_OPCODE_NEWNAME;
          decoder->state = NGHTTP2_HPACK_STATE_NEWNAME_CHECK_NAMELEN;
          ++p;
        } else {
          decoder->opcode = NGHTTP2_HPACK_OPCODE_INDNAME;
          decoder->state = NGHTTP2_HPACK_STATE_READ_INDEX;
          rstate->prefix = 6;
        }

        rstate->indexing = 1;
        rstate->never = 0;

        break;
      default:
        DEBUGF("decoder: indexed header field representation\n");

        decoder->opcode = NGHTTP2_HPACK_OPCODE_INDEXED;
        decoder->state = NGHTTP2_HPACK_STATE_READ_INDEX;
        rstate->prefix = 7;
      }

      rstate->left = 0;
      rstate->shift = 0;

      break;
    case NGHTTP2_HPACK_STATE_READ_TABLE_SIZE:
      nread = hpack_decoder_read_len(
        decoder, &rfin, p, last, 5,
        nghttp2_min(decoder->min_dtable_capacity,
                    decoder->ctx.hard_max_dtable_capacity));
      if (nread < 0) {
        rv = (int)nread;
        goto fail;
      }

      p += nread;

      if (!rfin) {
        goto almost_ok;
      }

      DEBUGF("decoder: table_size=%zu\n", rstate->left);

      decoder->min_dtable_capacity = UINT32_MAX;
      decoder->ctx.max_dtable_capacity = rstate->left;
      hpack_context_shrink_table_size(&decoder->ctx, NULL);
      decoder->state = NGHTTP2_HPACK_STATE_START;

      break;
    case NGHTTP2_HPACK_STATE_READ_INDEX:
      nread =
        hpack_decoder_read_len(decoder, &rfin, p, last, rstate->prefix,
                               hpack_context_get_max_index(&decoder->ctx));
      if (nread < 0) {
        rv = (int)nread;
        goto fail;
      }

      p += nread;

      if (!rfin) {
        goto almost_ok;
      }

      if (rstate->left == 0) {
        rv = NGHTTP2_ERR_HPACK_FATAL;
        goto fail;
      }

      DEBUGF("decoder: index=%zu\n", rstate->left);

      if (decoder->opcode == NGHTTP2_HPACK_OPCODE_INDEXED) {
        rstate->index = rstate->left - 1;

        hpack_decoder_emit_indexed(decoder, dest);

        decoder->state = NGHTTP2_HPACK_STATE_OPCODE;
        *pflags |= NGHTTP2_HPACK_DECODE_FLAG_EMIT;

        return p - src;
      }

      rstate->index = rstate->left - 1;
      decoder->state = NGHTTP2_HPACK_STATE_CHECK_VALUELEN;

      break;
    case NGHTTP2_HPACK_STATE_NEWNAME_CHECK_NAMELEN:
      hpack_decoder_set_huffman_encoded(decoder, p);
      decoder->state = NGHTTP2_HPACK_STATE_NEWNAME_READ_NAMELEN;
      rstate->left = 0;
      rstate->shift = 0;

      DEBUGF("decoder: huffman encoded=%d\n", rstate->huffman_encoded != 0);
    /* Fall through */
    case NGHTTP2_HPACK_STATE_NEWNAME_READ_NAMELEN:
      nread = hpack_decoder_read_len(decoder, &rfin, p, last, 7,
                                     NGHTTP2_HPACK_MAX_NV);
      if (nread < 0) {
        rv = (int)nread;
        goto fail;
      }

      p += nread;

      if (!rfin) {
        DEBUGF("decoder: integer not fully decoded. current=%zu\n",
               rstate->left);

        goto almost_ok;
      }

      decoder->state = NGHTTP2_HPACK_STATE_NEWNAME_READ_NAME;

      if (rstate->huffman_encoded) {
        nghttp2_hpack_huffman_decode_context_init(&rstate->huffman_ctx);

        rv = nghttp2_rcbuf_new(
          &rstate->name,
          nghttp2_hpack_huffman_estimate_decode_length(rstate->left) + 1, mem);
      } else {
        rv = nghttp2_rcbuf_new(&rstate->name, rstate->left + 1, mem);
      }

      if (rv != 0) {
        goto fail;
      }

      nghttp2_buf_wrap_init(&rstate->namebuf, rstate->name->base,
                            rstate->name->len);

      break;
    case NGHTTP2_HPACK_STATE_NEWNAME_READ_NAME:
      if (rstate->huffman_encoded) {
        nread =
          hpack_decoder_read_huffman_string(decoder, &rstate->namebuf, p, last);
      } else {
        nread = hpack_decoder_read_string(decoder, &rstate->namebuf, p, last);
      }

      if (nread < 0) {
        rv = (int)nread;
        goto fail;
      }

      p += nread;

      DEBUGF("decoder: %td bytes read\n", nread);

      if (rstate->left) {
        DEBUGF("decoder: still %zu bytes to go\n", rstate->left);

        goto almost_ok;
      }

      *rstate->namebuf.last = '\0';
      rstate->name->len = nghttp2_buf_len(&rstate->namebuf);

      decoder->state = NGHTTP2_HPACK_STATE_CHECK_VALUELEN;

      break;
    case NGHTTP2_HPACK_STATE_CHECK_VALUELEN:
      hpack_decoder_set_huffman_encoded(decoder, p);
      decoder->state = NGHTTP2_HPACK_STATE_READ_VALUELEN;
      rstate->left = 0;
      rstate->shift = 0;

      DEBUGF("decoder: huffman encoded=%d\n", rstate->huffman_encoded != 0);
    /* Fall through */
    case NGHTTP2_HPACK_STATE_READ_VALUELEN:
      nread = hpack_decoder_read_len(decoder, &rfin, p, last, 7,
                                     NGHTTP2_HPACK_MAX_NV);
      if (nread < 0) {
        rv = (int)nread;
        goto fail;
      }

      p += nread;

      if (!rfin) {
        goto almost_ok;
      }

      DEBUGF("decoder: valuelen=%zu\n", rstate->left);

      decoder->state = NGHTTP2_HPACK_STATE_READ_VALUE;

      if (rstate->huffman_encoded) {
        nghttp2_hpack_huffman_decode_context_init(&rstate->huffman_ctx);

        rv = nghttp2_rcbuf_new(
          &rstate->value,
          nghttp2_hpack_huffman_estimate_decode_length(rstate->left) + 1, mem);
      } else {
        rv = nghttp2_rcbuf_new(&rstate->value, rstate->left + 1, mem);
      }

      if (rv != 0) {
        goto fail;
      }

      nghttp2_buf_wrap_init(&rstate->valuebuf, rstate->value->base,
                            rstate->value->len);

      busy = 1;

      break;
    case NGHTTP2_HPACK_STATE_READ_VALUE:
      if (rstate->huffman_encoded) {
        nread = hpack_decoder_read_huffman_string(decoder, &rstate->valuebuf, p,
                                                  last);
      } else {
        nread = hpack_decoder_read_string(decoder, &rstate->valuebuf, p, last);
      }

      if (nread < 0) {
        rv = (int)nread;
        goto fail;
      }

      p += nread;

      DEBUGF("decoder: %td bytes read\n", nread);

      if (rstate->left) {
        DEBUGF("decoder: still %zu bytes to go\n", rstate->left);

        goto almost_ok;
      }

      *rstate->valuebuf.last = '\0';
      rstate->value->len = nghttp2_buf_len(&rstate->valuebuf);

      if (decoder->opcode == NGHTTP2_HPACK_OPCODE_NEWNAME) {
        rv = hpack_decoder_emit_newname(decoder, dest);
      } else {
        rv = hpack_decoder_emit_indname(decoder, dest);
      }

      if (rv != 0) {
        goto fail;
      }

      decoder->state = NGHTTP2_HPACK_STATE_OPCODE;
      *pflags |= NGHTTP2_HPACK_DECODE_FLAG_EMIT;

      return p - src;
    }
  }

  assert(p == last);

almost_ok:
  DEBUGF("decoder: all input bytes were processed\n");

  if (fin) {
    DEBUGF("decoder: fin set\n");

    if (decoder->state != NGHTTP2_HPACK_STATE_OPCODE &&
        decoder->state != NGHTTP2_HPACK_STATE_START) {
      DEBUGF("decoder: unacceptable state=%d\n", decoder->state);
      rv = NGHTTP2_ERR_HPACK_FATAL;

      goto fail;
    }

    *pflags |= NGHTTP2_HPACK_DECODE_FLAG_FINAL;

    decoder->state = NGHTTP2_HPACK_STATE_START;
  }

  return p - src;

fail:
  DEBUGF("decoder: error return %td\n", rv);

  decoder->ctx.bad = 1;

  return rv;
}

int nghttp2_hpack_encoder_write_indname(nghttp2_hpack_encoder *encoder,
                                        nghttp2_buf *buf, size_t idx,
                                        const nghttp2_nv *nv,
                                        int indexing_mode) {
  return hpack_encoder_write_indname(encoder, buf, idx, nv, indexing_mode);
}

int nghttp2_hpack_encoder_write_newname(nghttp2_hpack_encoder *encoder,
                                        nghttp2_buf *buf, const nghttp2_nv *nv,
                                        int indexing_mode) {
  return hpack_encoder_write_newname(encoder, buf, nv, indexing_mode);
}

int nghttp2_hpack_encoder_write_table_size(nghttp2_hpack_encoder *encoder,
                                           nghttp2_buf *buf,
                                           size_t table_size) {
  return hpack_encoder_write_table_size(encoder, buf, table_size);
}

nghttp2_ssize nghttp2_hpack_decode_length(uint32_t *dest, size_t *pshift,
                                          int *pfin, uint32_t initial,
                                          size_t shift, uint8_t *first,
                                          uint8_t *last, size_t prefix) {
  return decode_length(dest, pshift, pfin, initial, shift, first, last, prefix);
}

size_t nghttp2_hpack_encoder_get_num_table_entries(
  const nghttp2_hpack_encoder *encoder) {
  return hpack_context_get_max_index(&encoder->ctx);
}

static const nghttp2_hpack_nv *
hpack_context_get_table_entry(const nghttp2_hpack_context *ctx, size_t idx) {
  if (idx == 0) {
    return NULL;
  }

  --idx;

  if (!INDEX_RANGE_VALID(ctx, idx)) {
    return NULL;
  }

  return nghttp2_hpack_context_table_get(ctx, idx);
}

const nghttp2_hpack_nv *
nghttp2_hpack_encoder_get_table_entry(const nghttp2_hpack_encoder *encoder,
                                      size_t idx) {
  return hpack_context_get_table_entry(&encoder->ctx, idx);
}

size_t
nghttp2_hpack_encoder_get_dtable_size(const nghttp2_hpack_encoder *encoder) {
  return encoder->ctx.dtable_size;
}

size_t nghttp2_hpack_encoder_get_max_dtable_capacity(
  const nghttp2_hpack_encoder *encoder) {
  return encoder->ctx.max_dtable_capacity;
}

size_t nghttp2_hpack_decoder_get_num_table_entries(
  const nghttp2_hpack_decoder *decoder) {
  return hpack_context_get_max_index(&decoder->ctx);
}

const nghttp2_hpack_nv *
nghttp2_hpack_decoder_get_table_entry(const nghttp2_hpack_decoder *decoder,
                                      size_t idx) {
  return hpack_context_get_table_entry(&decoder->ctx, idx);
}

size_t
nghttp2_hpack_decoder_get_dtable_size(const nghttp2_hpack_decoder *decoder) {
  return decoder->ctx.dtable_size;
}

size_t nghttp2_hpack_decoder_get_max_dtable_capacity(
  const nghttp2_hpack_decoder *decoder) {
  return decoder->ctx.max_dtable_capacity;
}

void nghttp2_hpack_read_state_free(nghttp2_hpack_read_state *rstate) {
  nghttp2_rcbuf_decref(rstate->value);
  nghttp2_rcbuf_decref(rstate->name);
}

void nghttp2_hpack_read_state_reset(nghttp2_hpack_read_state *rstate) {
  rstate->name = NULL;
  rstate->value = NULL;
  nghttp2_buf_init(&rstate->namebuf);
  nghttp2_buf_init(&rstate->valuebuf);
  rstate->left = 0;
  rstate->prefix = 0;
  rstate->index = 0;
  rstate->never = 0;
  rstate->indexing = 0;
  rstate->huffman_encoded = 0;
}
